name              = "backtest-worker"
main              = "main.py"
compatibility_date = "2025-07-18"
compatibility_flags = ["python_workers"]

[build]
command = "pip install -r requirements.txt -t ."
