name: Deploy Cloudflare Worker

# 手動按下 “Run workflow” 時才執行
on:
  workflow_dispatch:

# 若之後想改成 push 自動部署，把下列區塊註解解除
#  push:
#    paths:
#      - "worker/**"
#      - "worker/wrangler.toml"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cloudflare Wrangler 3.x 需要 Node 20+
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Workers
        working-directory: worker          # 這裡放 wrangler.toml 的資料夾
        run: wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN:   ${{ secrets.CLOUDFLARE_API_TOKEN }}
