name: Update Stock Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # 每日 08:00 UTC

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - env:
          FMP_TOKEN: ${{ secrets.FMP_TOKEN }}
        run: python update_data.py

      - name: Commit & push (only when changed)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name  "GitHub Action"
          git checkout -b temp-data-branch
          git add -f data/
          if git diff --staged --quiet; then
            echo "No change – skip commit."
            exit 0
          fi
          git commit -m "chore: auto-update data $(date -u +'%F')"
          git push -f origin temp-data-branch:data

      - run: git gc --prune=now --aggressive
